# Configuration

locations:
  - name: Beyla
    lat: 8.1195
    lon: -8.5320
  - name: Boffa
    lat: 9.6667
    lon: -14.1833
  - name: Boke
    lat: 10.9370
    lon: -14.2906
  - name: Coyah
    lat: 9.7500
    lon: -13.3833
  - name: Conakry
    lat: 9.6412
    lon: -13.5784
  - name: Dabola
    lat: 10.7298
    lon: -11.1108
  - name: Dalaba
    lat: 10.4300
    lon: -12.3500
  - name: Dinguiraye
    lat: 11.5450
    lon: -10.6750
  - name: Faranah
    lat: 9.9057
    lon: -10.8000
  - name: Forecariah
    lat: 9.7890
    lon: -13.5148
  - name: Fria
    lat: 10.3675
    lon: -13.5842
  - name: Gaoual
    lat: 11.7500
    lon: -13.4333
  - name: Gueckedou
    lat: 8.5750
    lon: -9.1800
  - name: Kankan
    lat: 10.3852
    lon: -9.3057
  - name: Kerouane
    lat: 9.2536
    lon: -9.0129
  - name: Kindia
    lat: 10.0000
    lon: -12.8667
  - name: Kissidougou
    lat: 9.0500
    lon: -10.0833
  - name: Koubia
    lat: 11.5833
    lon: -11.8333
  - name: Koundara
    lat: 12.0833
    lon: -12.2982
  - name: Kouroussa
    lat: 10.1209
    lon: -9.5451
  - name: Labe
    lat: 11.3182
    lon: -12.2833
  - name: Lelouma
    lat: 11.4167
    lon: -12.6667
  - name: Lola
    lat: 8.1750
    lon: -8.6500
  - name: Macenta
    lat: 8.5500
    lon: -9.5167
  - name: Mamou
    lat: 10.1500
    lon: -12.0000
  - name: Mandiana
    lat: 10.6500
    lon: -9.3667
  - name: Mali
    lat: 12.0837
    lon: -12.2548
  - name: Nzerekore
    lat: 7.7562
    lon: -8.8174
  - name: Pita
    lat: 10.2000
    lon: -12.6000
  - name: Siguiri
    lat: 11.3110
    lon: -9.1067
  - name: Telimele
    lat: 10.6333
    lon: -13.3500
  - name: Tougue
    lat: 11.4667
    lon: -11.6000
  - name: Yomou
    lat: 7.5696
    lon: -9.2592


# Format: YYYYMMDD
start_date: 20000101

# Format: YYYYMMDD
end_date: 20240101

# Output directory for weather records
output_dir: ./data
